# Generated by Django 2.0.7 on 2018-07-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('log_text', models.CharField(max_length=5000)),
                ('severity', models.PositiveSmallIntegerField(default=6)),
            ],
        ),
    ]
